LIB=		scgi

CFLAGS+=	-I../include

SRCS+=		scgi.c
SRCS+=		scgi-helpers.c
SRCS+=		scgi-header.c
SRCS+=		scgi-header-ct.c
SRCS+=		scgi-cookie.c
SRCS+=		scgi-header-cookie.c
SRCS+=		scgi-header-status.c
SRCS+=		scgi-header-location.c
SRCS+=		scgi-buffer.c


.include <bsd.lib.mk>
