LIB=		scgi

CFLAGS+=	-I../include

SRCS+=		scgi.c
SRCS+=		scgi-helpers.c
SRCS+=		scgi-header.c
SRCS+=		scgi-header-ct.c
SRCS+=		scgi-cookie.c
SRCS+=		scgi-header-cookie.c

SHLIB_MAJOR=	0.1.1

.include <bsd.lib.mk>
